### ISSUE TITLE
Error when adding new satellite

### ISSUE THREAD

**Issue by xcrespo** [satnet-project/server#10]
After selecting the TLE group (i.e. Cubesats, wheather...), clicking on "TLE Id" does nothing. The following error is shown on the console:

```
Uncaught TypeError: Cannot read property 'nextSibling' of undefined (nya-bs-select.min.js:6)
```

**Comment by rtp-calpoly** [comment]
This problem might be caused due to the expiration of the session. That feature might be added later after the first release.

**Comment by rtp-calpoly** [comment]
Exception handling enhanced when using the embeded PyEphem simulator. This enhancement (already included both at the master and development branches) has solved this issue.
