### ISSUE TITLE
Error when adding a new GS

### ISSUE THREAD

**Issue by xcrespo** [satnet-project/server#11]
The following error is obtained when adding a new GS from the GUI. 
```
The satellite seems to stay always below your horizon
```
Despite the error, the GS is correctly added to the database.

**Comment by xcrespo** [comment]
A similar error raises when trying to add a LEOP cluster from the admin interface. In this case the cluster is not incorporated to the database.

**Comment by rtp-calpoly** [comment]
Could you please post a more complete description of the issue? It would be awesome if you could upload the GS location and the TLEs that you are using.

**Comment by xcrespo** [comment]
This issue seems to be solved in the latest version. I think the error was produced due to an unclean database.

**Comment by rtp-calpoly** [comment]
Yes, no more problems like this have appeared since the last database sync.
