### ISSUE TITLE
Upgrade to Python 3

### ISSUE THREAD

**Issue by rtp-calpoly** [satnet-project/server#19]
Upgrade to Python 3 since all the libraries support it.

**Comment by rtp-calpoly** [comment]
Upgrade finished!

**Comment by xcrespo** [comment]
Twisted does not provide full support for Python 3, although they are working on it. More specifically, I can't run UnitTests with Twisted Trial tool ([more info](https://twistedmatrix.com/trac/wiki/Plan/Python3))

**Comment by rtp-calpoly** [comment]
@xcrespo : this issue concerns only to the server project. If you want to account for it on the protocol, please create a similar issue for that project as well. It is a pity that Github does not have the possibility of managing from here issues for several projects at the same time.
