### ISSUE TITLE
JRPC Protocol Connectivity

### ISSUE THREAD

**Issue by rtubio** [satnet-project/server#29]
Create the following methods to allow the protocol accessing the database through JRPC, avoiding the limitations set by the usage of Python 2 in the Protocol. The functions are the following:

* **get_slot_info(slot_id)**:
    * shall return an error if the slot is not yet operational,
    * otherwise it shall return the following JSON object:
        * **state**: slot[0].state,
        * **gs_username** : slot[0].groundstation_channel.groundstation_set.all()[0].user.username,
        * **sc_username** : slot[0].spacecraft_channel.spacecraft_set.all()[0].user.username,
        * **end** : slot[0].end
* **store_message(slot_id, upwards, forwarded, timestamp, message)**:
    * shall return a boolean that indicates whether the message was properly stored or not.

To log in, we will use the method from rpc4django: **system.login(username, password)**

**Comment by rtp-calpoly** [comment]
There are different possibilities when implementing this methods, the protocol repository will implement those detailed below but we are open to other suggestions:

- ```get_slot_info(slot_id)``` shall return an error if the slot is not yet operational. Otherwise it shall return the following JSON object:
```
  {
    "state" : slot[0].state,
    "gs_username" : slot[0].groundstation_channel.groundstation_set.all()[0].user.username,
    "sc_username" : slot[0].spacecraft_channel.spacecraft_set.all()[0].user.username,
    "end" : slot[0].end
  }
```
- ```store_message(slot_id, upwards, forwarded, timestamp, message)``` shall return a JSON object containing a boolean indicating if the message was or not stored ```{"result" : result}```

For logging in we will use the method given by rpc4django: ```system.login(username, password)```.

**Comment by rtp-calpoly** [comment]
Methods already implemented, it should be possible to eliminate the dependencies of the protocol with the server form now on.

**Comment by rtp-calpoly** [comment]
@sgongar : try to migrate the current code you have for the protocol by using these methods in order to satisfy the dependencies with the old server DB model manager. Let me know how it goes.

**Comment by sgongar** [comment]
@rtp-calpoly I'm working on it!

**Comment by rtp-calpoly** [comment]
@sgongar , have you experiencied any problems with this issue?

**Comment by rtp-calpoly** [comment]
@sgongar , have you experienced any problems with this issue?

**Comment by rtubio** [comment]
@sgongar , I am going to close this issue. Please re-open it if you understand that we need to make any additional changes.
