### ISSUE TITLE
REST Auth Framework

### ISSUE THREAD

**Issue by rtp-calpoly** [satnet-project/server#4]
Remove dependency from the server's code.

**Comment by rtp-calpoly** [comment]
@xcrespo : could you please check whether these dependencies have already been completely removed from the development branch of the server?

**Comment by xcrespo** [comment]
The url "api-auth/" should be removed from website/urls.py. The file services/accounts/serializers.py is also unnecessary.

**Comment by rtp-calpoly** [comment]
Done.
